### ISSUE TITLE
When mapping dependencies with moduleRefs, Maureen would like the output variable name to default to the input variable name if not provided

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/action-module-metadata-create#104]
This would provide a short-hand to simplify the hand-coded portion of the module metadata a little.

For example:

```yaml
variables:
  - name: host_key
    moduleRef:
      id: database-secret
      output: host_key
```

could be simplified to

```yaml
variables:
  - name: host_key
    moduleRef:
      id: database-secret
```

This change would reduce the amount of information that would be manually provided and makes reduces the opportunities for making mistakes
